export const ActionTypes = {
  // SET_PRODUCTS: 'SET_PRODUCTS',
  // SELECTED_PRODUCT: 'SELECTED_PRODUCT',
  // REMOVE_SELECTED_PRODUCT: 'REMOVE_SELECTED_PRODUCT',
  LOAD_CURRENT_ITEM: 'LOAD_CURRENT_ITEM',
  UPDATE_ITEM_PRICE: 'UPDATE_ITEM_PRICE'
};
